add traceability for source code that builds this

diff --git a/lib/bin/rebuild_phusion_passenger_image b/lib/bin/rebuild_phusion_passenger_image
--- a/lib/bin/rebuild_phusion_passenger_image
+++ b/lib/bin/rebuild_phusion_passenger_image
@@ -5,21 +5,24 @@ BASE_DIR="$(dirname $(dirname $THIS_DIR))"
 
 . $BASE_DIR/lib/bash_include/config.bash
 . $BASE_DIR/lib/bash_include/github.bash
+. $BASE_DIR/lib/bash_include/bash_utils.bash
 
 PHUSION_PASSENGER_IMAGE_NAME="$(new_image_name_from_repo $PHUSION_PASSENGER_IMAGE_REPO)"
 IMAGE_FULLNAME="$DOCKER_NAMESPACE/$PHUSION_PASSENGER_IMAGE_NAME"
 
-SOURCE_DIR="$IMAGE_REPOS_DIR/$(dir_name_from_repo $PHUSION_PASSENGER_IMAGE_REPO)"
-github_checkout "$PHUSION_PASSENGER_IMAGE_REPO" "$SOURCE_DIR" "$PHUSION_PASSENGER_IMAGE_REPO_RELEASE_TAG" || exit 1
-cd "$SOURCE_DIR" || exit 1
+github_checkout "$PHUSION_PASSENGER_IMAGE_REPO" "$PHUSION_PASSENGER_IMAGE_SOURCE_DIR" "$PHUSION_PASSENGER_IMAGE_REPO_RELEASE_TAG" || exit 1
+cd "$PHUSION_PASSENGER_IMAGE_SOURCE_DIR" || exit 1
+
+export PATH="$BASE_DIR/lib/docker_shim:$PATH" # use a docker shim to filter out arguments we don't like # TODO: DELETE after fast test cycles are not needed
 
 DOCKER_FILE="./image/Dockerfile"
 sed -i "s~^FROM[[:space:]].\{1,\}$~FROM $DOCKER_NAMESPACE/phusion_baseimage:$PHUSION_BASE_IMAGE_VERSION~" $DOCKER_FILE
 
-# TODO: upgrade? warn of available upgrades?: MAKE_TARGET=build_ruby26
-# TODO: maybe use as an alternate since it's got all the rubies in it?: MAKE_TARGET=build_full
 MAKE_TARGET=build_ruby25
 MAKE_OUTPUT="$(make $MAKE_TARGET NAME="$IMAGE_FULLNAME")" || exit 1
 echo "$MAKE_OUTPUT"
 
-echo "$MAKE_OUTPUT" | grep "^Successfully tagged $IMAGE_FULLNAME.*:$PHUSION_PASSENGER_IMAGE_VERSION\$" >/dev/null || { echo ERROR: $(basename $0): image not tagged as expected; exit 1; }
+TAG_REPORT="$(echo "$MAKE_OUTPUT" | grep "^Successfully tagged $IMAGE_FULLNAME.*:$PHUSION_PASSENGER_IMAGE_VERSION\$")" || { echo ERROR: $(basename $0): image not tagged as expected; exit 1; }
+
+echo $TAG_REPORT > "$PHUSION_PASSENGER_IMAGE_SOURCE_STATE_REPORT"
+report_local_repository_state "$PHUSION_PASSENGER_IMAGE_SOURCE_DIR" >> "$PHUSION_PASSENGER_IMAGE_SOURCE_STATE_REPORT"
