even more disk space mitigation

diff --git a/ci/clean b/ci/clean
--- a/ci/clean
+++ b/ci/clean
@@ -6,6 +6,7 @@ THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
 BASE_DIR="$(dirname $THIS_DIR)"
 . $BASE_DIR/lib/bash_include/config.bash
 
+$BIN/delete_test_image || { echo "ERROR: $(basename $0): FAILED to delete test image" >&2; exit 1; }
 rm -rf $BASE_DIR/tmp
 IMAGES_TO_REMOVE="$(for IMAGE_NAME in $MAIN_IMAGE_FULLNAME $PHUSION_BASE_IMAGE_NAME $PHUSION_PASSENGER_IMAGE_NAME;do docker images --format '{{.Repository}}:{{.Tag}}' | grep $IMAGE_NAME; done)"
 if [ -n "$IMAGES_TO_REMOVE" ]; then
