testing git tagging

diff --git a/ci/publish b/ci/publish
--- a/ci/publish
+++ b/ci/publish
@@ -3,6 +3,7 @@
 THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
 BASE_DIR="$(dirname $THIS_DIR)"
 
+# TODO: should this fail if you try to run it locally instead of from jenkins? at least if you don't pass -f/--force? maybe we should bake username/hostname into the image for traceability instead?
 # TODO: publish version 1.0.
 
 function main {
@@ -13,10 +14,14 @@ function main {
         echo "ERROR: $(basename $0): version $version has already been published. Please edit version.txt according to semver and try again." >&2
     else
         docker tag "singlecellportal/$IMAGE_NAME:latest" "singlecellportal/$IMAGE_NAME:$version" || { echo "ERROR: $(basename $0): failed to tag $IMAGE_NAME with $version ">&2; exit 1; }
-        docker image ls | grep "\\b$IMAGE_NAME\\b" | grep "$version" || exit 1 #confirm taggging worked
+        docker image ls | grep "\\b$IMAGE_NAME\\b" | grep "\\b$version\\b" || exit 1 #confirm taggging worked
         docker push "singlecellportal/$IMAGE_NAME:latest" || { echo "ERROR: $(basename $0): failed to push $IMAGE_NAME:latest ">&2; exit 1; }
         docker push "singlecellportal/$IMAGE_NAME:$version" || { echo "ERROR: $(basename $0): failed to push $IMAGE_NAME:$version ">&2; exit 1; }
-        # TODO: git[hub] tag release
+
+        # TODO: test git[hub] release tag from jenkins job, which might not work the same:
+        git tag "$version" || exit 1
+        git push origin "$version" || exit 1
+
     fi
 }
 
