provide a clean way to specify versions, and make sure they are the ones that actually get downloaded, rebuilt, and used

diff --git a/ci/publish b/ci/publish
--- a/ci/publish
+++ b/ci/publish
@@ -3,20 +3,22 @@
 THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
 BASE_DIR="$(dirname $THIS_DIR)"
 
+. $BASE_DIR/lib/bash_include/config.bash
+
+# TODO: (?): docker login
 # TODO: should this fail if you try to run it locally instead of from jenkins? at least if you don't pass -f/--force? maybe we should bake username/hostname into the image for traceability instead?
 # TODO: publish version 1.0.
 
 function main {
-    IMAGE_NAME="rails-baseimage"
     version=$(cat $BASE_DIR/version.txt)
 
-    if docker_image_has_been_published "hub.docker.com" "singlecellportal/$IMAGE_NAME" "$version" ; then
+    if docker_image_has_been_published "hub.docker.com" "$MAIN_IMAGE_FULLNAME" "$version" ; then
         echo "ERROR: $(basename $0): version $version has already been published. Please edit version.txt according to semver and try again." >&2
     else
-        docker tag "singlecellportal/$IMAGE_NAME:latest" "singlecellportal/$IMAGE_NAME:$version" || { echo "ERROR: $(basename $0): failed to tag $IMAGE_NAME with $version ">&2; exit 1; }
-        docker image ls | grep "\\b$IMAGE_NAME\\b" | grep "\\b$version\\b" || exit 1 #confirm taggging worked
-        docker push "singlecellportal/$IMAGE_NAME:latest" || { echo "ERROR: $(basename $0): failed to push $IMAGE_NAME:latest ">&2; exit 1; }
-        docker push "singlecellportal/$IMAGE_NAME:$version" || { echo "ERROR: $(basename $0): failed to push $IMAGE_NAME:$version ">&2; exit 1; }
+        docker tag "$MAIN_IMAGE_FULLNAME:latest" "$MAIN_IMAGE_FULLNAME:$version" || { echo "ERROR: $(basename $0): failed to tag $MAIN_IMAGE_NAME with $version ">&2; exit 1; }
+        docker image ls | grep "\\b$MAIN_IMAGE_FULLNAME\\b" | grep "\\b$version\\b" || exit 1 #confirm taggging worked
+        docker push "$MAIN_IMAGE_FULLNAME:latest" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_NAME:latest ">&2; exit 1; }
+        docker push "$MAIN_IMAGE_FULLNAME:$version" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_NAME:$version ">&2; exit 1; }
 
         # TODO: test git[hub] release tag from jenkins job, which might not work the same:
         git tag "$version" || exit 1
diff --git a/lib/bin/rebuild_phusion_baseimage b/lib/bin/rebuild_phusion_baseimage
--- a/lib/bin/rebuild_phusion_baseimage
+++ b/lib/bin/rebuild_phusion_baseimage
@@ -1,25 +1,21 @@
 #!/bin/bash
 
-# TODO: DRY this script as much as possible with the other script for building a phusion package
-
-GITHUB_REPO="phusion/baseimage-docker"
-RELEASE_TAG="0.11"
-
-THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
+THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
 BASE_DIR="$(dirname $(dirname $THIS_DIR))"
-IMAGE_REPOS_DIR="$BASE_DIR/tmp" # TODO: DRY with other scripts
 
+. $BASE_DIR/lib/bash_include/config.bash
 . $BASE_DIR/lib/bash_include/github.bash
 
-IMAGE_NAME="$(new_image_name_from_repo $GITHUB_REPO)"
+IMAGE_FULLNAME="$DOCKER_NAMESPACE/$PHUSION_BASE_IMAGE_NAME"
 
-# TODO: function extract?:
-SOURCE_DIR="$IMAGE_REPOS_DIR/$(dir_name_from_repo $GITHUB_REPO)"
-github_checkout $GITHUB_REPO $SOURCE_DIR "$RELEASE_TAG" || exit 1
-cd $SOURCE_DIR || exit 1
+SOURCE_DIR="$IMAGE_REPOS_DIR/$(dir_name_from_repo $PHUSION_BASE_IMAGE_REPO)"
+github_checkout "$PHUSION_BASE_IMAGE_REPO" "$SOURCE_DIR" "$PHUSION_BASE_IMAGE_REPO_RELEASE_TAG" || exit 1
+cd "$SOURCE_DIR" || exit 1
 
 export PATH="$BASE_DIR/lib/docker_shim:$PATH" # use a docker shim to filter out arguments we don't like
 
 export PLATFORM=amd64 QEMU_ARCH=amd64 TAG_ARCH=amd64
-make build BASE_IMAGE="marketplace.gcr.io/google/ubuntu1804:latest" NAME="singlecellportal/$IMAGE_NAME" || exit 1
-docker image ls | grep "\\b$IMAGE_NAME\\b" || exit 1 # TODO: | grep version
+MAKE_OUTPUT="$(make build BASE_IMAGE="$BASE_IMAGE" NAME="$IMAGE_FULLNAME" )" || exit 1
+echo "$MAKE_OUTPUT" # TODO: DELETE?
+
+echo "$MAKE_OUTPUT" | grep "^Successfully tagged $IMAGE_FULLNAME:$PHUSION_BASE_IMAGE_VERSION\$" >/dev/null || { echo ERROR: $(basename $0): image not tagged as expected; exit 1; }
diff --git a/lib/bin/rebuild_phusion_passenger_image b/lib/bin/rebuild_phusion_passenger_image
--- a/lib/bin/rebuild_phusion_passenger_image
+++ b/lib/bin/rebuild_phusion_passenger_image
@@ -1,30 +1,25 @@
 #!/bin/bash
 
-# TODO: DRY this script as much as possible with the other script for building a phusion package
-
-GITHUB_REPO="phusion/passenger-docker"
-RELEASE_TAG="rel-1.0.6"
-
-THIS_DIR="$(cd "$(dirname "$0")"; pwd)"
+THIS_DIR="$(cd "$(dirname "$BASH_SOURCE")"; pwd)"
 BASE_DIR="$(dirname $(dirname $THIS_DIR))"
-IMAGE_REPOS_DIR="$BASE_DIR/tmp" # TODO: DRY with other scripts
 
+. $BASE_DIR/lib/bash_include/config.bash
 . $BASE_DIR/lib/bash_include/github.bash
 
-IMAGE_NAME="$(new_image_name_from_repo $GITHUB_REPO)"
+PHUSION_PASSENGER_IMAGE_NAME="$(new_image_name_from_repo $PHUSION_PASSENGER_IMAGE_REPO)"
+IMAGE_FULLNAME="$DOCKER_NAMESPACE/$PHUSION_PASSENGER_IMAGE_NAME"
 
-# TODO: function extract?:
-SOURCE_DIR="$IMAGE_REPOS_DIR/$(dir_name_from_repo $GITHUB_REPO)"
-github_checkout $GITHUB_REPO $SOURCE_DIR "$RELEASE_TAG" || exit 1
-cd $SOURCE_DIR || exit 1
-
-export PATH="$BASE_DIR/lib/docker_shim:$PATH" # use a docker shim to filter out arguments we don't like # TODO: DELETE after fast test cycles are not needed
+SOURCE_DIR="$IMAGE_REPOS_DIR/$(dir_name_from_repo $PHUSION_PASSENGER_IMAGE_REPO)"
+github_checkout "$PHUSION_PASSENGER_IMAGE_REPO" "$SOURCE_DIR" "$PHUSION_PASSENGER_IMAGE_REPO_RELEASE_TAG" || exit 1
+cd "$SOURCE_DIR" || exit 1
 
 DOCKER_FILE="./image/Dockerfile"
-sed -i 's~^FROM[[:space:]].\{1,\}$~FROM singlecellportal/phusion_baseimage:0.11-amd64~' $DOCKER_FILE # TODO: deal with versions # TODO: this would be a good place to add code to record it
+sed -i "s~^FROM[[:space:]].\{1,\}$~FROM $DOCKER_NAMESPACE/phusion_baseimage:$PHUSION_BASE_IMAGE_VERSION~" $DOCKER_FILE
 
 # TODO: upgrade? warn of available upgrades?: MAKE_TARGET=build_ruby26
 # TODO: maybe use as an alternate since it's got all the rubies in it?: MAKE_TARGET=build_full
 MAKE_TARGET=build_ruby25
-make $MAKE_TARGET NAME="singlecellportal/$IMAGE_NAME" || exit 1
-docker image ls | grep "\\b$IMAGE_NAME\\b" || exit 1 # TODO: | grep version
+MAKE_OUTPUT="$(make $MAKE_TARGET NAME="$IMAGE_FULLNAME")" || exit 1
+echo "$MAKE_OUTPUT" # TODO: DELETE?
+
+echo "$MAKE_OUTPUT" | grep "^Successfully tagged $IMAGE_FULLNAME.*:$PHUSION_PASSENGER_IMAGE_VERSION\$" >/dev/null || { echo ERROR: $(basename $0): image not tagged as expected; exit 1; }
