test jenkins job again, without trying to git tag releases

diff --git a/ci/publish b/ci/publish
--- a/ci/publish
+++ b/ci/publish
@@ -5,7 +5,6 @@ BASE_DIR="$(dirname $THIS_DIR)"
 
 . $BASE_DIR/lib/bash_include/config.bash
 
-# TODO: (?): docker login
 # TODO: should this fail if you try to run it locally instead of from jenkins? at least if you don't pass -f/--force? maybe we should bake username/hostname into the image for traceability instead?
 # TODO: publish version 1.0.
 
@@ -19,14 +18,8 @@ function main {
         docker tag "$MAIN_IMAGE_FULLNAME:latest" "$MAIN_IMAGE_FULLNAME:$version" || { echo "ERROR: $(basename $0): failed to tag $MAIN_IMAGE_NAME with $version ">&2; exit 1; }
         docker image ls | grep "\\b$MAIN_IMAGE_FULLNAME\\b" | grep "\\b$version\\b" || exit 1 #confirm taggging worked
         docker push "$MAIN_IMAGE_FULLNAME:latest" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_NAME:latest ">&2; exit 1; }
-        docker push "$MAIN_IMAGE_FULLNAME:$version" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_NAME:$version ">&2; exit 1; }
-
-        # TODO: test git[hub] release tag from jenkins job, which might not work the same:
-        # TODO: this is also problematic, because if not run from jenkins, what's to say there aren't local changes?
-        echo DEBUG: running: git tag $version
-        git tag "$version" || exit 1
-        echo DEBUG: running: git push origin $version
-        git push origin "$version" || exit 1
+        docker push "$MAIN_IMAGE_FULLNAME:$version" || { echo "ERROR: $(basename $0): failed to push $MAIN_IMAGE_FULLNAME:$version ">&2; exit 1; }
+        echo published $MAIN_IMAGE_FULLNAME:$version
 
     fi
 }
