enabling more checks

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -13,14 +13,14 @@ BIN="$BASE_DIR/lib/bin"
 
 function main {
     test_serving_a_page
-
+    test_for_unpublished_changes
     exit 0
 }
 
 function test_serving_a_page {
     $BIN/build_test_image || { echo "ERROR: $(basename $0): FAILED to build test image" >&2; exit 1; }
 
-    TEST_CONTAINER_NAME="${TEST_IMAGE_NAME}_testing_container"
+    TEST_CONTAINER_NAME="${TEST_IMAGE_NAME}_container"
     docker stop $TEST_CONTAINER_NAME 2>/dev/null
     echo DEBUG: trying docker run...
     docker run --rm -d \
@@ -30,11 +30,10 @@ function test_serving_a_page {
     || exit_with_error_message "FAILED to run test image $MAIN_IMAGE_FULLNAME:candidate $(grep FROM Dockerfile|head -n 1)  (at $BASH_SOURCE:$LINENO)"
 
     echo sleeping for 30 seconds to allow the test containter to come up.... at $(date);sleep 30;echo done sleeping at $(date);echo "--------------------" & # TODO TODO: DELETE
-    curl -v 'http://localhost:9980/index.nginx-debian.html' || { echo "ERROR ($?): FAILED to curl page from test container! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; } #TODO: TEST (based on /var/) # TODO: container name, not localhost ;\
+    curl -v 'http://localhost:9980/index.nginx-debian.html' || { echo "ERROR ($?): FAILED to curl page from test container! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; } # TODO: container name, not localhost ;\
     echo DEBUG: it seems that curl worked.
 
     docker stop $TEST_CONTAINER_NAME || { echo "ERROR: could not stop container \"$TEST_CONTAINER_NAME\"! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; }
-
 }
 
 function test_for_unpublished_changes {
