dealing with disk space even more aggressively

diff --git a/ci/test b/ci/test
--- a/ci/test
+++ b/ci/test
@@ -29,11 +29,22 @@ function test_serving_a_page {
         $TEST_IMAGE_FULLNAME \
     || exit_with_error_message "FAILED to run test image $MAIN_IMAGE_FULLNAME:candidate $(grep FROM Dockerfile|head -n 1)  (at $BASH_SOURCE:$LINENO)"
 
-    echo sleeping for 30 seconds to allow the test containter to come up.... at $(date);sleep 30;echo done sleeping at $(date);echo "--------------------" & # TODO TODO: DELETE
-    curl -v 'http://localhost:9980/index.nginx-debian.html' || { echo "ERROR ($?): FAILED to curl page from test container! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; } # TODO: container name, not localhost ;\
-    echo DEBUG: it seems that curl worked.
+    TEST_CONTAINER_IPADDR="$(docker inspect -f "{{.NetworkSettings.IPAddress }}" $TEST_CONTAINER_NAME)"
+    sleep_for_at_least=60 # TODO TODO: DELETE, simplify, or at least pare down the amount of time
+    echo sleeping for $sleep_for_at_least seconds to allow the test containter to come up.... at $(date);sleep $sleep_for_at_least;echo done sleeping at $(date);echo "--------------------" # TODO TODO: DELETE, simplify, or at least pare down the amount of time
+
+    curl_output="$(curl -v --connect-timeout 2 --retry 6 --retry-delay 5 "http://$TEST_CONTAINER_IPADDR/index.nginx-debian.html" 2>&1 )"; curl_exit_code="$?" # TODO: container name, not localhost ;\
 
     docker stop $TEST_CONTAINER_NAME || { echo "ERROR: could not stop container \"$TEST_CONTAINER_NAME\"! (at $BASH_SOURCE:$LINENO)" >&2; exit 1; }
+    $BIN/delete_test_image || { echo "ERROR: $(basename $0): FAILED to delete test image" >&2; exit 1; }
+
+    if [ "$curl_exit_code" -eq 0 ];then
+        echo "curl succeeded!" >&2
+    else
+        echo "$curl_output"| tail -n 3 >&2 # TODO: limit output
+        echo "ERROR ($curl_exit_code): FAILED to curl page from test container! (at $BASH_SOURCE:$LINENO)" >&2
+        exit 1
+    fi
 }
 
 function test_for_unpublished_changes {
