testing catching unstable builds

diff --git a/.github/workflows/publish-base-docker-image.yml b/.github/workflows/publish-base-docker-image.yml
--- a/.github/workflows/publish-base-docker-image.yml
+++ b/.github/workflows/publish-base-docker-image.yml
@@ -26,8 +26,21 @@ jobs:
         run: |
           # auth into GCR via Docker with token from service account
           AUTH_TOKEN=$(docker run --rm ${{ env.IMAGE_NAME }} gcloud auth print-access-token)
+          # need separate logins for gcr.io & marketplace.gcr.io
           echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://gcr.io
-      - name: Test candidate base Docker image
-        run: ci/gha.build-and-test.bash
+          echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://marketplace.gcr.io
+      - name: Build and publish base Docker image
+        id: build-and-publish
+        run: |
+          set +e # continue on error to capture exit code
+          ci/gha.publish-image.bash
+          exitcode="$?"
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+      - name: Check for unstable build
+        if: ${{ steps.build-and-publish.exitcode == '99' }}
+        run: |
+          echo "### WARNING: THERE ARE UPDATED DEPENDENCIES, BUT THIS IMAGE WILL STILL FUNCTION ###"
+          echo "### MARKING AS SUCCESSFUL ###"
+          exit 0
 
 
diff --git a/.github/workflows/test-base-docker-image.yml b/.github/workflows/test-base-docker-image.yml
--- a/.github/workflows/test-base-docker-image.yml
+++ b/.github/workflows/test-base-docker-image.yml
@@ -30,8 +30,17 @@ jobs:
           # need separate logins for gcr.io & marketplace.gcr.io
           echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://gcr.io
           echo $AUTH_TOKEN | docker login -u oauth2accesstoken --password-stdin https://marketplace.gcr.io
-      - name: Build base Docker image
+      - name: Test candidate base Docker image
+        id: build-and-test
         run: |
+          set +e # continue on error to capture exit code
           ci/gha.build-and-test.bash
-
+          exitcode="$?"
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+      - name: Check for unstable build
+        if: ${{ steps.build-and-test.exitcode == '99' }}
+        run: |
+          echo "### WARNING: THERE ARE UPDATED DEPENDENCIES, BUT THIS IMAGE WILL STILL FUNCTION ###"
+          echo "### MARKING AS SUCCESSFUL ###"
+          exit 0
 
